name: workflow overview

on: 
  workflow_dispatch

jobs:
  a_simple_job:
    name: my simple job name
    runs-on: ubuntu-latest
    steps: 
      - name : name of my step
        id: StepID
        run: echo "This is the first step from the first job"
      - name : step with another shell
        id: shellStep
        shell: python
        run: print ("this step is using python shell")
        
        
      
